name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - feature/docs
    paths:
      - 'docs/**'  # Only trigger when docs are updated
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
          run_install: false

      - name: Install dependencies
        run: |
          cd docs
          pnpm install

      - name: Build documentation
        run: |
          cd docs
          pnpm run docs:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist   # The folder the action should deploy
          branch: gh-pages               # The branch the action should deploy to
