name: Publish Packages

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment:
        required: true
        type: string
        description: 'Either "development" or "production"'

jobs:
  publish_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: |
            packages/*/dist

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
          run_install: false

      - name: Restore Frontend Cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            .pnpm-store
            packages/*/node_modules
          key: ${{ runner.os }}-pnpm-${{ github.ref_name }}-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Publish Packages
        run: |
          pnpm changeset publish --no-git-tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
